In [12]:
def ReLU(z):
    return np.maximum(0,z)

def ReLU_derivative(z):
    return 1 if z.any()>0 else 0

In [13]:
import numpy as np
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])
training_outputs = np.array([[0,1,1,0]]).T
np.random.seed(1)
synaptic_weights = 2*np.random.random((3,1))-1
print('Random Starting synaptic weights: ')
print(synaptic_weights)

for iteration in range(100):
    input_layer = training_inputs
    outputs=ReLU(np.dot(input_layer,synaptic_weights))
    error=training_outputs-outputs
    adjustments=error*ReLU_derivative(outputs)
    synaptic_weights=synaptic_weights + np.dot(input_layer.T,adjustments)

print('Synaptic_weights after training:')
print(synaptic_weights)

print('Outputs after training:')
print(outputs)

Random Starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic_weights after training:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Outputs after training:
[[0.]
 [0.]
 [0.]
 [0.]]
