In [10]:
print ('This is a code for simple feebforward neural network')
import numpy as np
# sigmoid activation function
def sigmoid (x):
    return 1/(1+np.exp(-x))
def sigmoid_derivative(x):
    return x*(1-x)
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])
training_outputs = np.array([[0,1,1,0]]).T
np.random.seed(1)
synaptic_weights = 2*np.random.random((3,1))-1
print('Random Starting synaptic weights: ')
print(synaptic_weights)

for iteration in range(100):
    input_layer = training_inputs
    outputs=sigmoid(np.dot(input_layer,synaptic_weights))
    error=training_outputs-outputs
    adjustments=error*sigmoid_derivative(outputs)
    synaptic_weights=synaptic_weights + np.dot(input_layer.T,adjustments)

print('Synaptic_weights after training:')
print(synaptic_weights)

print('Outputs after training:')
print(outputs)


This is a code for simple feebforward neural network
Random Starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic_weights after training:
[[ 4.62128737]
 [-0.20338466]
 [-2.09325311]]
Outputs after training:
[[0.11035029]
 [0.91041229]
 [0.92564882]
 [0.09193919]]


In [ ]:
input_layer=training_inputs

In [ ]:
outputs=sigmoid(np.dot(input_layer,synaptic_weights))

In [ ]:
print(outputs)