In [37]:
import numpy as np
def tanh(x):
    return(np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))
def tanh_derivative(x):
    return(1-((np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x)))**2)

In [38]:
import numpy as np
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])
training_outputs = np.array([[0,1,1,0]]).T
np.random.seed(1)
synaptic_weights = 2*np.random.random((3,1))-1
print('Random Starting synaptic weights: ')
print(synaptic_weights)



Random Starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [39]:

for iteration in range(1):
    input_layer = training_inputs
    outputs=ReLU(np.dot(input_layer,synaptic_weights))
    error=training_outputs-outputs
    adjustments=error*dReLU(outputs)
    synaptic_weights=synaptic_weights + np.dot(input_layer.T,adjustments)


In [40]:
print('Synaptic_weights after training:')
print(synaptic_weights)

print('Outputs after 1 iterations:')
print(outputs)

Synaptic_weights after training:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Outputs after 1 iterations:
[[0.]
 [0.]
 [0.]
 [0.]]


In [29]:

for iteration in range(2):
    input_layer = training_inputs
    outputs=tanh(np.dot(input_layer,synaptic_weights))
    error=training_outputs-outputs
    adjustments=error*tanh_derivative(outputs)
    synaptic_weights=synaptic_weights + np.dot(input_layer.T,adjustments)
print('Outputs after 2nd iterations:')
print(outputs)

Outputs after 2nd iterations:
[[-0.38944444]
 [ 0.9774006 ]
 [ 0.91429317]
 [ 0.26509163]]


In [30]:

for iteration in range(10):
    input_layer = training_inputs
    outputs=tanh(np.dot(input_layer,synaptic_weights))
    error=training_outputs-outputs
    adjustments=error*tanh_derivative(outputs)
    synaptic_weights=synaptic_weights + np.dot(input_layer.T,adjustments)
print('Outputs after 10th iterations:')
print(outputs)

Outputs after 10th iterations:
[[0.31155067]
 [0.99227668]
 [0.98862666]
 [0.47514336]]


In [31]:

for iteration in range(5000):
    input_layer = training_inputs
    outputs=tanh(np.dot(input_layer,synaptic_weights))
    error=training_outputs-outputs
    adjustments=error*tanh_derivative(outputs)
    synaptic_weights=synaptic_weights + np.dot(input_layer.T,adjustments)
print('Outputs after 5000 iterations:')
print(outputs)

Outputs after 5000 iterations:
[[0.33037173]
 [0.99997198]
 [0.99995862]
 [0.49158032]]


In [32]:

for iteration in range(50000):
    input_layer = training_inputs
    outputs=tanh(np.dot(input_layer,synaptic_weights))
    error=training_outputs-outputs
    adjustments=error*tanh_derivative(outputs)
    synaptic_weights=synaptic_weights + np.dot(input_layer.T,adjustments)
print('Outputs after 10000 iterations:')
print(outputs)

Outputs after 10000 iterations:
[[0.33025048]
 [0.99999744]
 [0.99999622]
 [0.49137694]]
